const tools={
qr:{title:"QR Code Generator",desc:"Turn text or a URL into a downloadable QR code.",render:()=>`
<div class="tool-card"><div class="tool-head"><h2>QR Code Generator</h2><p>Paste a URL or text, then tap Generate. Your QR code appears below.</p></div>
<div class="stack"><div><label for="qr-input">Text or URL</label><input id="qr-input" value="https://example.com" placeholder="https://example.com"></div>
<div class="actions"><button class="btn" id="qr-generate" type="button">Generate QR Code</button><button class="btn secondary" id="qr-download" type="button">Download PNG</button></div>
<div id="qr-status" class="status">Ready to generate.</div>
<div class="result qr-wrap"><div id="qr-output" class="qr-box"><span id="qr-placeholder">Your QR code will appear here</span></div></div></div></div>`,
init:()=>{const out=document.querySelector("#qr-output"),input=document.querySelector("#qr-input"),status=document.querySelector("#qr-status"),download=document.querySelector("#qr-download");const make=()=>{out.innerHTML="";if(typeof QRCode==="undefined"){status.className="status bad";status.textContent="QR engine failed to load. Refresh and try again.";out.textContent="QR generator unavailable";return}try{new QRCode(out,{text:input.value.trim()||" ",width:220,height:220,correctLevel:QRCode.CorrectLevel.M});status.className="status good";status.textContent="QR code generated ✓"}catch(e){status.className="status bad";status.textContent="Could not generate QR code.";out.textContent="Generation failed"}};document.querySelector("#qr-generate").onclick=make;download.onclick=()=>{const img=out.querySelector("img");const canvas=out.querySelector("canvas");const src=img?.src||canvas?.toDataURL?.("image/png");if(!src){status.className="status bad";status.textContent="Generate a QR code first.";return}const a=document.createElement("a");a.href=src;a.download="codekit-qr.png";a.click()};make()}},
json:{title:"JSON Formatter",desc:"Format, validate, and minify JSON.",render:()=>`
<div class="tool-card"><div class="tool-head"><h2>JSON Formatter</h2><p>Pretty-print JSON or crush it back down to one line.</p></div>
<div><label for="json-input">JSON</label><textarea id="json-input">{"hello":"world","numbers":[1,2,3]}</textarea></div><div class="actions"><button class="btn" id="json-format">Format</button><button class="btn secondary" id="json-minify">Minify</button></div><div id="json-status" class="status"></div></div>`,
init:()=>{const input=document.querySelector("#json-input"),status=document.querySelector("#json-status");const run=pretty=>{try{const data=JSON.parse(input.value);input.value=JSON.stringify(data,null,pretty?2:0);status.className="status good";status.textContent="Valid JSON ✓"}catch(e){status.className="status bad";status.textContent="Invalid JSON: "+e.message}};document.querySelector("#json-format").onclick=()=>run(true);document.querySelector("#json-minify").onclick=()=>run(false)}},
uuid:{title:"UUID Generator",desc:"Generate unique UUID v4 identifiers.",render:()=>`
<div class="tool-card"><div class="tool-head"><h2>UUID Generator</h2><p>Generate IDs for users, records, sessions, files, and whatever else needs a name.</p></div>
<div class="result"><div id="uuid-value" class="big-value"></div></div><div class="actions"><button class="btn" id="uuid-generate">Generate UUID</button><button class="btn secondary" id="uuid-copy">Copy</button></div><div id="uuid-status" class="status"></div></div>`,
init:()=>{const value=document.querySelector("#uuid-value"),status=document.querySelector("#uuid-status");const make=()=>{value.textContent=crypto.randomUUID?crypto.randomUUID():fallbackUuid();status.textContent=""};const fallbackUuid=()=>{let a=crypto.getRandomValues(new Uint8Array(16));a[6]=a[6]&15|64;a[8]=a[8]&63|128;const h=[...a].map(x=>x.toString(16).padStart(2,"0")).join("");return h.slice(0,8)+"-"+h.slice(8,12)+"-"+h.slice(12,16)+"-"+h.slice(16,20)+"-"+h.slice(20)};document.querySelector("#uuid-generate").onclick=make;document.querySelector("#uuid-copy").onclick=async()=>{try{await navigator.clipboard.writeText(value.textContent);status.className="status good";status.textContent="Copied ✓"}catch{status.textContent="Copy failed. Select the UUID manually."}};make()}},
base64:{title:"Base64 Encoder / Decoder",desc:"Encode text to Base64 or decode Base64 back to text.",render:()=>`
<div class="tool-card"><div class="tool-head"><h2>Base64</h2><p>Encode or decode UTF-8 text.</p></div><div><label for="b64-input">Input</label><textarea id="b64-input" placeholder="Type something..."></textarea></div><div class="actions"><button class="btn" id="b64-encode">Encode</button><button class="btn secondary" id="b64-decode">Decode</button></div><div><label for="b64-output" style="margin-top:18px">Output</label><textarea id="b64-output" readonly></textarea></div><div id="b64-status" class="status"></div></div>`,
init:()=>{const i=document.querySelector("#b64-input"),o=document.querySelector("#b64-output"),s=document.querySelector("#b64-status");const enc=new TextEncoder();const dec=new TextDecoder();document.querySelector("#b64-encode").onclick=()=>{const bytes=enc.encode(i.value);let bin="";bytes.forEach(b=>bin+=String.fromCharCode(b));o.value=btoa(bin);s.className="status good";s.textContent="Encoded ✓"};document.querySelector("#b64-decode").onclick=()=>{try{const bin=atob(i.value.trim());const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));o.value=dec.decode(bytes);s.className="status good";s.textContent="Decoded ✓"}catch(e){s.className="status bad";s.textContent="Invalid Base64"}}}},
url:{title:"URL Encoder",desc:"Safely encode or decode URL components.",render:()=>`
<div class="tool-card"><div class="tool-head"><h2>URL Encoder</h2><p>Handle spaces, symbols, query values, and other URL characters.</p></div><div><label for="url-input">Input</label><textarea id="url-input" placeholder="https://example.com/hello world?x=1&y=2"></textarea></div><div class="actions"><button class="btn" id="url-encode">Encode</button><button class="btn secondary" id="url-decode">Decode</button></div><div><label for="url-output" style="margin-top:18px">Output</label><textarea id="url-output" readonly></textarea></div><div id="url-status" class="status"></div></div>`,
init:()=>{const i=document.querySelector("#url-input"),o=document.querySelector("#url-output"),s=document.querySelector("#url-status");const run=(fn)=>{try{o.value=fn(i.value);s.className="status good";s.textContent="Done ✓"}catch{s.className="status bad";s.textContent="Invalid URL text"}};document.querySelector("#url-encode").onclick=()=>run(encodeURIComponent);document.querySelector("#url-decode").onclick=()=>run(decodeURIComponent)}},
color:{title:"Color Converter",desc:"Convert HEX colors to RGB and HSL.",render:()=>`
<div class="tool-card"><div class="tool-head"><h2>Color Converter</h2><p>Drop in a HEX color and get the common formats back.</p></div><div class="row"><div><label for="color-input">HEX</label><input id="color-input" value="#63e6a3"></div><div class="result" style="margin:0"><div id="color-values" class="big-value" style="font-size:15px"></div></div></div><div id="color-preview" class="color-preview"></div><div id="color-status" class="status"></div></div>`,
init:()=>{const i=document.querySelector("#color-input"),v=document.querySelector("#color-values"),p=document.querySelector("#color-preview"),s=document.querySelector("#color-status");const run=()=>{let h=i.value.trim().replace("#","");if(!/^[0-9a-fA-F]{6}$/.test(h)){s.className="status bad";s.textContent="Use a 6-digit HEX color, like #63e6a3.";return}const r=parseInt(h.slice(0,2),16),g=parseInt(h.slice(2,4),16),b=parseInt(h.slice(4,6),16);const rr=r/255,gg=g/255,bb=b/255,max=Math.max(rr,gg,bb),min=Math.min(rr,gg,bb),d=max-min;let hh=0,ss=0,l=(max+min)/2;if(d){ss=d/(1-Math.abs(2*l-1));switch(max){case rr:hh=60*(((gg-bb)/d)%6);break;case gg:hh=60*((bb-rr)/d+2);break;default:hh=60*((rr-gg)/d+4)}}if(hh<0)hh+=360;v.textContent=`RGB: ${r}, ${g}, ${b}\nHSL: ${Math.round(hh)}°, ${Math.round(ss*100)}%, ${Math.round(l*100)}%`;p.style.background="#"+h;s.className="status good";s.textContent="Valid color ✓"};i.addEventListener("input",run);run()}},
timestamp:{title:"Timestamp Converter",desc:"Convert Unix timestamps to readable dates and back.",render:()=>`
<div class="tool-card"><div class="tool-head"><h2>Timestamp Converter</h2><p>Unix time in seconds, UTC date, and your local date.</p></div><div class="row"><div><label for="ts-input">Unix timestamp</label><input id="ts-input" inputmode="numeric" placeholder="1760000000"></div><div><label for="date-input">ISO date</label><input id="date-input" placeholder="2026-10-05T12:00:00Z"></div></div><div class="actions"><button class="btn" id="ts-now">Use current time</button><button class="btn secondary" id="ts-from-unix">Timestamp → Date</button><button class="btn secondary" id="ts-from-date">Date → Timestamp</button></div><div id="ts-output" class="result"></div></div>`,
init:()=>{const t=document.querySelector("#ts-input"),d=document.querySelector("#date-input"),o=document.querySelector("#ts-output");document.querySelector("#ts-now").onclick=()=>{const now=Date.now();t.value=Math.floor(now/1000);d.value=new Date(now).toISOString();o.textContent="Current time loaded ✓"};document.querySelector("#ts-from-unix").onclick=()=>{const n=Number(t.value);if(!Number.isFinite(n)){o.textContent="Enter a valid Unix timestamp.";return}const date=new Date(n*1000);o.textContent=date.toString()+"\nUTC: "+date.toISOString()};document.querySelector("#ts-from-date").onclick=()=>{const date=new Date(d.value);if(Number.isNaN(date.getTime())){o.textContent="Enter a valid date.";return}t.value=Math.floor(date.getTime()/1000);o.textContent="Unix timestamp: "+t.value}}
,shortener:{title:"URL Shortener",desc:"Turn long URLs into compact CodeKit links.",render:()=>`
<div class="tool-card"><div class="tool-head"><h2>URL Shortener</h2><p>Paste a long URL and CodeKit creates a short link automatically.</p></div>
<div class="stack"><div><label for="shortener-input">Long URL</label><input id="shortener-input" type="url" placeholder="https://example.com/a/really/long/url"></div>
<div class="actions"><button class="btn" id="shortener-create">Shorten URL</button></div>
<div id="shortener-status" class="status"></div>
<div id="shortener-result" class="result" hidden><label for="shortener-output">Your short URL</label><input id="shortener-output" readonly><div class="actions"><button class="btn secondary" id="shortener-copy">Copy</button><a id="shortener-open" class="btn secondary" target="_blank" rel="noopener">Open</a></div><div id="shortener-destination" class="status"></div></div></div></div>`,
init:()=>{const input=document.querySelector("#shortener-input"),create=document.querySelector("#shortener-create"),status=document.querySelector("#shortener-status"),result=document.querySelector("#shortener-result"),output=document.querySelector("#shortener-output"),destination=document.querySelector("#shortener-destination"),open=document.querySelector("#shortener-open");const endpoint="https://fbqzavqemtezakmmysak.supabase.co/functions/v1/shortener";create.onclick=async()=>{const value=input.value.trim();if(!value){status.className="status bad";status.textContent="Enter a URL first.";return}try{new URL(value)}catch{status.className="status bad";status.textContent="Enter a valid URL.";return}create.disabled=true;status.className="status";status.textContent="Creating short link...";result.hidden=true;try{const res=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:value})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Could not create link.");output.value=data.shortUrl;destination.textContent="Destination: "+data.targetUrl;open.href=data.shortUrl;result.hidden=false;status.className="status good";status.textContent="Short link created ✓"}catch(e){status.className="status bad";status.textContent=e.message||"Shortener unavailable."}finally{create.disabled=false}};document.querySelector("#shortener-copy").onclick=async()=>{try{await navigator.clipboard.writeText(output.value);status.className="status good";status.textContent="Copied ✓"}catch{status.className="status bad";status.textContent="Copy failed. Select the link manually."}}}}
};
const area=document.querySelector("#tool-area"),title=document.querySelector("#page-title");
function openTool(name){const tool=tools[name]||tools.qr;document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.tool===name));title.textContent=tool.title;area.innerHTML=tool.render();tool.init?.()}
document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>openTool(b.dataset.tool)));
openTool("qr");